### ISSUE TITLE
Unknown class in Interface Builder file.

### ISSUE THREAD

**Issue by abnoy** [DuncanMC/CropImg#2]
I dragged UIView into my storyboard then change the type to CroppableImageView in the Identity Inspector. 

Whenever I bring up the view, it's blank, I also get this error in the debug area:

Unknown class _TtC7CropImg18CroppableImageView in Interface Builder file

Also, when I try to connect the UIView to an IBOutlet property in my ViewController I get this error:

Use of undeclared type 'CroppableImageView'

**Comment by DuncanMC** [comment]
This is not meant as a drop-in component. It's a demonstration of how to do image cropping in Swift. You'll need to drag the source files `CornerpointClientProtocol.swift`, `CornerpointView.swift`, `CroppableImageViewDelegateProtocol.swift`, and `CroppableImageView.swift` into your project before you can add views of that type to your storyboard.

**Comment by abnoy** [comment]
I see, I feel like a dummy now, thank you for the clarification.
