### ISSUE TITLE
Blank CroppableImageView in ViewController.

### ISSUE THREAD

**Issue by Slogbelly** [DuncanMC/CropImg#3]
Good day sir.

I dropped in all the necessary files, for cornerpoint, croppableimageview, and ViewController.swift files, and everything works wonderfully except 1 thing.
The image (either default or one selected) won't display in the CroppableImageView.  However, if you drag a square and hit "crop image" it will actually take a snapshot of what you selected, from the image, so it is there, just can't see it, which has me baffled. 
I've checked IBOutlet connections, names, etc and cannot track down what I did wrong.

My storyboard is slightly different as it is part of a tab bar controller and "ViewController" is the 2nd view controller on the tab bar, so it's not a standalone view controller.  Would that make any different?  Don't see why it would.

Thank your for your time.
Wendell

**Comment by DuncanMC** [comment]
What happens if you run the original unmodified project?

**Comment by Slogbelly** [comment]
I forgot to mention that.  It works fine under the original project, which is making it extra frustrating.

**Comment by Slogbelly** [comment]
You may disregard this.  I finally tracked down what the problem was.  ME!
When I added the view I didn't change the background to "Clear color", it was still left as the default White background.  DUH.  It's always that 1 little thing isn't it?
